package main

import (
	"flag"
	"fmt"
)

func main() {
	role := flag.String("role", "", "iran or outside")
	proto := flag.String("proto", "tcp", "protocol")
	listen := flag.String("listen", "", "listen address")
	connect := flag.String("connect", "", "connect address")
	flag.Parse()

	fmt.Println("iPmartnet CLI started")
	fmt.Println("role   :", *role)
	fmt.Println("proto  :", *proto)
	fmt.Println("listen :", *listen)
	fmt.Println("connect:", *connect)
}
